export const AUTOGEN_HEADER_BLOCKLIST = [
  'access-control-expose-headers', 
  'access-control-allow-credentials', 
  'host',
  'proxy-connection',
  'sec-ch-ua',
  'sec-ch-ua-mobile',
  'user-agent',
  'sec-ch-ua-platform',
  'origin',
  'sec-fetch-site',
  'sec-fetch-mode',
  'sec-fetch-dest',
  'referer',
  'accept-encoding',
  'accept-language',
  'date',
  'x-powered-by'
]